"""credits table

Revision ID: 119101b7b875
Revises: 20a39c297655
Create Date: 2026-07-26 11:31:51.193099+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "119101b7b875"
down_revision: str | None = "20a39c297655"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("source_appointment_id", sa.Integer(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_appointment_id"],
            ["appointments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credits_client_id"), "credits", ["client_id"], unique=False)
    op.create_index(op.f("ix_credits_is_used"), "credits", ["is_used"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_credits_is_used"), table_name="credits")
    op.drop_index(op.f("ix_credits_client_id"), table_name="credits")
    op.drop_table("credits")
    # ### end Alembic commands ###
