"""initial schema: users, appointments, availability_slots

Revision ID: 206417ece486
Revises:
Create Date: 2026-07-25 22:23:00.742841+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "206417ece486"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("role", sa.Enum("cliente", "admin", name="userrole"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("visit_type", sa.Enum("prima", "controllo", name="visittype"), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending_payment", "confirmed", "cancelled", name="appointmentstatus"),
            nullable=False,
        ),
        sa.Column("price_eur", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_appointments_client_id"), "appointments", ["client_id"], unique=False)
    op.create_index(
        op.f("ix_appointments_scheduled_at"), "appointments", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_appointments_status"), "appointments", ["status"], unique=False)
    op.create_table(
        "availability_slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("held_by_appointment_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["held_by_appointment_id"],
            ["appointments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_availability_slots_is_open"), "availability_slots", ["is_open"], unique=False
    )
    op.create_index(
        op.f("ix_availability_slots_starts_at"), "availability_slots", ["starts_at"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_availability_slots_starts_at"), table_name="availability_slots")
    op.drop_index(op.f("ix_availability_slots_is_open"), table_name="availability_slots")
    op.drop_table("availability_slots")
    op.drop_index(op.f("ix_appointments_status"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_scheduled_at"), table_name="appointments")
    op.drop_index(op.f("ix_appointments_client_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###

    # On PostgreSQL, dropping the tables leaves the ENUM types behind, which would
    # break a re-upgrade with "type already exists". Drop them explicitly. This is a
    # no-op on SQLite, where enum columns are stored as text.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("appointmentstatus", "visittype", "userrole"):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
