"""orders table

Revision ID: 20a39c297655
Revises: f1ffbe932291
Create Date: 2026-07-26 11:07:59.797309+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20a39c297655"
down_revision: str | None = "f1ffbe932291"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "formula", sa.Enum("single", "subscription", name="orderformula"), nullable=False
        ),
        sa.Column("pickup", sa.Enum("mattina", "pomeriggio", name="pickupslot"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending_payment", "paid", "cancelled", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["nutrition_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_client_id"), "orders", ["client_id"], unique=False)
    op.create_index(op.f("ix_orders_plan_id"), "orders", ["plan_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_plan_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_client_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###

    # On PostgreSQL, dropping the table leaves the ENUM types behind, which would
    # break a re-upgrade with "type already exists". Drop them explicitly. This is a
    # no-op on SQLite, where enum columns are stored as text.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("orderstatus", "pickupslot", "orderformula"):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
