"""payments table

Revision ID: 65ef700c31d0
Revises: d3b282e879a1
Create Date: 2026-07-26 12:49:04.565159+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65ef700c31d0"
down_revision: str | None = "d3b282e879a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("apple_pay", "google_pay", "card", name="paymentmethod"),
            nullable=False,
        ),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("provider_token", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("status", sa.Enum("succeeded", "failed", name="paymentstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_appointment_id"), "payments", ["appointment_id"], unique=False
    )
    op.create_index(op.f("ix_payments_client_id"), "payments", ["client_id"], unique=False)
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_client_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_appointment_id"), table_name="payments")
    op.drop_table("payments")
    # ### end Alembic commands ###

    # On PostgreSQL, dropping the table leaves the ENUM types behind, which would
    # break a re-upgrade with "type already exists". Drop them explicitly. This is a
    # no-op on SQLite, where enum columns are stored as text.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in ("paymentstatus", "paymentmethod"):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
