"""nutrition_plans table

Revision ID: 88bf64de43e0
Revises: 34d424954cde
Create Date: 2026-07-26 08:00:49.819597+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88bf64de43e0"
down_revision: str | None = "34d424954cde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nutrition_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("daily_kcal", sa.Integer(), nullable=False),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_nutrition_plans_client_id"), "nutrition_plans", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_nutrition_plans_is_active"), "nutrition_plans", ["is_active"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_nutrition_plans_is_active"), table_name="nutrition_plans")
    op.drop_index(op.f("ix_nutrition_plans_client_id"), table_name="nutrition_plans")
    op.drop_table("nutrition_plans")
    # ### end Alembic commands ###
