"""notifications table

Revision ID: d3b282e879a1
Revises: 119101b7b875
Create Date: 2026-07-26 12:15:40.507347+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3b282e879a1"
down_revision: str | None = "119101b7b875"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "appointment_reminder",
                "order_deadline",
                "box_ready",
                "box_proposal",
                name="notificationkind",
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("dedupe_key", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id", "dedupe_key", name="uq_notifications_client_key"),
    )
    op.create_index(
        op.f("ix_notifications_client_id"), "notifications", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_dedupe_key"), "notifications", ["dedupe_key"], unique=False
    )
    op.create_index(op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_dedupe_key"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_client_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###

    # On PostgreSQL, dropping the table leaves the ENUM type behind, which would
    # break a re-upgrade with "type already exists". Drop it explicitly. This is a
    # no-op on SQLite, where enum columns are stored as text.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="notificationkind").drop(bind, checkfirst=True)
