#!/usr/bin/env bash
# Package the repo's Claude Code configuration into a distributable zip.
#
#   ./scripts/package-claude-config.sh            # write docs/dist/meridia-claude-config.zip
#   ./scripts/package-claude-config.sh --check    # verify the committed zip is up to date
#
# The output is byte-reproducible: file order is sorted and every entry gets a
# fixed timestamp, so regenerating from unchanged sources yields an identical
# blob and git stores no new object.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BUNDLE_NAME="meridia-claude-config"
OUT_DIR="docs/dist"
OUT_ZIP="${OUT_DIR}/${BUNDLE_NAME}.zip"
FIXED_TIMESTAMP="202001010000.00"   # touch -t format; keeps the archive reproducible

CHECK_MODE=0
[[ "${1:-}" == "--check" ]] && CHECK_MODE=1

# Machine-local or runtime state — never shipped in the bundle.
EXCLUDES=(
    ".claude/settings.local.json"
    ".claude/locks/branch-locks.json"
)

is_excluded() {
    local candidate="$1" excluded
    for excluded in "${EXCLUDES[@]}"; do
        [[ "$candidate" == "$excluded" ]] && return 0
    done
    case "$candidate" in
        .claude/locks/grade-skip-*) return 0 ;;
    esac
    return 1
}

STAGE="$(mktemp -d)"
trap 'chmod -R u+w "$STAGE" 2>/dev/null || true; rm -rf -- "$STAGE"' EXIT
DEST="${STAGE}/${BUNDLE_NAME}"
mkdir -p "$DEST"

# Source of truth: files tracked by git, so an untracked scratch file never
# sneaks into a published bundle.
FILES=()
while IFS= read -r file; do
    is_excluded "$file" && continue
    FILES+=("$file")
done < <(git ls-files .claude CLAUDE.md | LC_ALL=C sort)

if [[ ${#FILES[@]} -eq 0 ]]; then
    echo "error: no Claude configuration files found under .claude/" >&2
    exit 1
fi

for file in "${FILES[@]}"; do
    mkdir -p "${DEST}/$(dirname "$file")"
    cp -p "$file" "${DEST}/${file}"
done
chmod +x "${DEST}/.claude/hooks/"*.sh

# --- generated bundle README -------------------------------------------------

# Agent handle (@egidio, @ezio, …) comes from the `name:` frontmatter key.
agent_handle() {
    local handle
    handle="$(awk -F': *' '/^name: /{print $2; exit}' "$1")"
    [[ -n "$handle" ]] && printf '@%s' "$handle"
}

# Render one directory as an indented listing, annotated where we can derive it.
list_dir() {
    local dir="$1" annotate="$2" path base pad handle
    while IFS= read -r path; do
        base="$(basename "$path")"
        if [[ "$annotate" == "agents" ]]; then
            handle="$(agent_handle "$path")"
            pad=$((30 - ${#base}))
            [[ $pad -lt 1 ]] && pad=1
            printf '│   ├── %s%*s%s\n' "$base" "$pad" "" "$handle"
        else
            printf '│   ├── %s\n' "$base"
        fi
    done < <(printf '%s\n' "${FILES[@]}" | grep "^${dir}/[^/]*$" | LC_ALL=C sort)
}

{
    cat <<'HEADER'
# Meridia — Claude Code configuration bundle

Portable copy of the Claude Code setup for the `mickgian/nutritionApp` (Meridia)
repo: the project instructions plus the whole `.claude/` tree.

This file and the archive around it are generated by
`scripts/package-claude-config.sh` — do not hand-edit either one.

## Contents

```
CLAUDE.md                     Project instructions (loaded automatically by Claude Code)
.claude/
├── settings.json             Hook wiring + permissions
├── subagent-names.json       Agent roster
├── SQLMODEL_QUICKREF.md      SQLModel cheat sheet for backend agents
├── agents/                   subagent definitions
HEADER
    list_dir ".claude/agents" agents
    echo '├── commands/                 slash commands'
    list_dir ".claude/commands" plain
    echo '├── hooks/                    shell hooks (executable)'
    list_dir ".claude/hooks" plain
    echo '├── rubrics/                  grading rubrics for @collaudatore'
    list_dir ".claude/rubrics" plain
    echo '├── workflows/                process docs'
    list_dir ".claude/workflows" plain
    echo '├── locks/                    branch reservation template'
    list_dir ".claude/locks" plain
    echo '└── one-time-fixes/           log for throwaway ops artifacts'
    list_dir ".claude/one-time-fixes" plain
    cat <<'FOOTER'
```

## Installing into another repo

1. Unzip and copy `CLAUDE.md` and `.claude/` to the target repo root.
2. Restore the executable bit on the hooks if your unzip tool dropped it:
   `chmod +x .claude/hooks/*.sh`
3. Adjust `CLAUDE.md` — it is Meridia-specific (Python/FastAPI + Kotlin
   Multiplatform, Italian user-facing strings, the agent roster and workflow).
4. `.claude/settings.json` references hooks via
   `$CLAUDE_PROJECT_DIR/.claude/hooks/…`, so no path edits are needed.

## Notes

- `.claude/settings.local.json` and the runtime lock files are excluded — they
  are machine-local state, not shared configuration.
- No credentials or secrets are present in this bundle.
FOOTER
} > "${DEST}/README.md"

# --- reproducible archive ----------------------------------------------------

find "$STAGE" -exec touch -t "$FIXED_TIMESTAMP" {} +

ZIP_TARGET="${STAGE}/${BUNDLE_NAME}.zip"
( cd "$STAGE" && find "$BUNDLE_NAME" -type f | LC_ALL=C sort | zip -qX -9 "${BUNDLE_NAME}.zip" -@ )

mkdir -p "$OUT_DIR"

if [[ $CHECK_MODE -eq 1 ]]; then
    if [[ ! -f "$OUT_ZIP" ]]; then
        echo "STALE: ${OUT_ZIP} does not exist. Run ./scripts/package-claude-config.sh" >&2
        exit 1
    fi
    if ! cmp -s "$ZIP_TARGET" "$OUT_ZIP"; then
        echo "STALE: ${OUT_ZIP} does not match the current .claude/ configuration." >&2
        echo "Run ./scripts/package-claude-config.sh and commit the result." >&2
        exit 1
    fi
    echo "OK: ${OUT_ZIP} is up to date (${#FILES[@]} config files)."
    exit 0
fi

cp "$ZIP_TARGET" "$OUT_ZIP"
echo "Wrote ${OUT_ZIP} (${#FILES[@]} config files + README.md)."
